# -*- coding: utf-8 -*-
"""piworks-task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJ0EetYE_Aeny1Oyvje4_x2OrXVpBiA6

Please implement a small program that reads the input file and produces the desired outputs for below questions, optimized for speed of operation. (Preferred language is Python or C#)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")
df = pd.read_csv("country_vaccination_stats.csv")
print(df)

df.shape

df.info()

df.isnull().sum()

countries = df['country'].unique()
countries

"""Code Implementation Task: Implement code to fill the missing data (impute) in daily_vaccinations column per country with the minimum daily vaccination number of relevant countries.  
Note: If a country does not have any valid vaccination number yet, fill it with “0” (zero). 

"""

df.groupby(['country'])['daily_vaccinations'].min()

for i in countries:
    min_vac = df[df['country']==i]['daily_vaccinations'].min()
    if np.isnan(min_vac):
        values = {'daily_vaccinations': 0}
    else:
        values = {'daily_vaccinations': min_vac}
    df[df['country'] == i] = df[df['country'] == i].fillna(value=values)

df.head(10)

"""Code Implementation Task: Implement code to list the top-3 countries with highest median daily vaccination numbers by considering missing values imputed version of dataset."""

df.groupby(['country'])['daily_vaccinations'].median()

df.groupby(['country'])['daily_vaccinations'].median().head(3)

df.groupby(['country'])['daily_vaccinations'].median().tail(3)

first_three_median = {}
for i in countries[0:3]:
    first_three_median[df[df['country']==i].median()[0]]=i

for i in countries[3:]:
    if df[df['country']==i].median()[0] > min(first_three_median.keys()):
        first_three_median.pop(min(first_three_median.keys()))
        first_three_median[df[df['country']==i].median()[0]]=i

first_three_median

"""What is the number of total vaccinations done on 1/6/2021 (MM/DD/YYYY) by considering missing values imputed version of dataset?"""

df[df['date']=="1/6/2021"].daily_vaccinations.sum()